# Generated by Django 4.0 on 2022-01-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_result_student', to='students.student'),
        ),
    ]
