# Generated by Django 4.0 on 2022-01-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentresult_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizz_mark', models.CharField(max_length=255)),
                ('quizz_total', models.CharField(max_length=255)),
                ('group_mark', models.CharField(max_length=255)),
                ('group_total', models.CharField(max_length=255)),
                ('presentation_mark', models.CharField(max_length=255)),
                ('presentation_total', models.CharField(max_length=255)),
                ('test_mark', models.CharField(max_length=255)),
                ('test_total', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_work_student', to='students.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
