# Generated by Django 4.0 on 2022-01-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentcoursework'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursework',
            name='final_mark',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
