# Generated by Django 4.0 on 2022-01-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('student_id_number', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('next_of_kin', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('next_of_kin_phone_number', models.CharField(max_length=255)),
                ('archieved', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('archieve_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('module_name', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('gpe', models.CharField(max_length=255)),
                ('credits', models.CharField(max_length=255)),
                ('archieved', models.BooleanField(default=False)),
                ('archieve_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
