# Generated by Django 4.0 on 2022-01-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_student_id_studentresult_student_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=255),
        ),
    ]
