# Generated by Django 4.0 on 2022-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='student_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
