# Generated by Django 4.0 on 2022-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_archieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='archieve',
            name='typ',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
