# Generated by Django 4.0 on 2022-01-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_archieve_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archieve',
            name='bay',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archieve',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archieve',
            name='shelf',
            field=models.PositiveIntegerField(),
        ),
    ]
