# Generated by Django 4.0 on 2022-01-07 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lecturercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lecturer', to='courses.course'),
        ),
    ]
